import { Composition } from "remotion";
// VIDEO_TO_TSX:IMPORTS
// Do not delete this marker. Compositions generated by `scripts/video-to-tsx.mjs`
// will insert their imports above this line.

export const RemotionRoot: React.FC = () => {
  return (
    <>
      {/* VIDEO_TO_TSX:COMPOSITIONS */}
      {/* Compositions generated by the video-to-tsx tool will be inserted above
          this marker. Do not delete the marker. */}
    </>
  );
};
